name: Deploy to Now
on: [push]

jobs:
  filteroutmaster:
    name: Filter out master branch
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Filter out master branch
        uses: actions/bin/filter@master
        with:
          args: "branch master"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy on Now.sh - Static Production Build
        run: now -t Qa58IyKnoxHEiSbpiarLBA0c
