name: Deploy to Now
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy on Now.sh - Static Production Build
        run: now -t Qa58IyKnoxHEiSbpiarLBA0c
