name: Deploy to Now
on: 
  repository_dispatch:
    types: example-event

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Deploy on Now.sh - Static Production Build
        run: vercel deploy -t Qa58IyKnoxHEiSbpiarLBA0c --prod --no-clipboard --confirm
